#!/bin/sh /etc/rc.common
PhienBan="20200327a"
USE_PROCD=1

# starts before dnsmasq starts
START=18
# stops before networking stops
STOP=89

Chay=/usr/sbin/dns
OS=`uname -m`; x64="x86_64"; arm="armv7l"; Android="aarch64"
if [ $OS == $x64 ]; then CauHinh=/root/dns/CauHinh.toml; fi
if [ $OS == $arm ]; then CauHinh=/sd/dns/CauHinh.toml; fi

start_service() {
        procd_open_instance
        procd_set_param command "$Chay" -config "$CauHinh"
        procd_set_param file "$CauHinh"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
        procd_close_instance
}
