#!/bin/sh /etc/rc.common
PhienBan="20200411a"
USE_PROCD=1

# starts before dnsmasq starts
START=18
# stops before networking stops
STOP=89

Chay=/usr/sbin/dns
if [ -f "/root/dns/CauHinh.toml" ]; then CauHinh=/root/dns/CauHinh.toml; fi
if [ -f "/sd/dns/CauHinh.toml" ]; then CauHinh=/sd/dns/CauHinh.toml; fi
if [ -f "/config/dns/CauHinh.toml" ]; then CauHinh=/config/dns/CauHinh.toml; fi

start_service() {
        procd_open_instance
        procd_set_param command "$Chay" -config "$CauHinh"
        procd_set_param file "$CauHinh"
        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
        procd_close_instance
}
